version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=speedrun
      - POSTGRESQL_PASSWORD=gofast
      - POSTGRESQL_DATABASE=src2
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  db:
    driver: local
